### ISSUE TITLE
TA_1.0.0_d mode problem

### ISSUE THREAD

**Issue by hilsenna** [drmaize/ThermoAlign#5]
Hello,
We tried to use the program but we couldn't make it. Could you please check the errors and help me to fix this? Our input contains only one chromosome, thus we changed the "chr_no" and "no_chrs_in_genome " to  "1"  at 'ThermoAlign/TA_codes/parameters.py' file.

```
root@0347c74eafd1:/TA_codes# ./pipeline.sh
../sample_vcf/processed_vcf_files/chr1
Traceback (most recent call last):
  File "TRS.py", line 111, in <module>
    indel_snp_gap_info = variant_mask(chr_no, start_pos, stop_pos, variant_path, refDB_path, out_path, time_stamp, variant_mask_condition) 
  File "TRS.py", line 44, in variant_mask
    df = pd.read_csv(variant_path+filename, sep='\t', header=0) 
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 315, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 645, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 799, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1213, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 358, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3427)
  File "pandas/parser.pyx", line 628, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6861)
IOError: File ../sample_vcf/processed_vcf_files/chr1 does not exist
BLAST Database error: No alias or index file found for nucleotide database [../sample_genome/zmv2all] in search path [/TA_codes::]
Traceback (most recent call last):
  File "PSE.py", line 217, in <module>
    min_pimer_len    =    len(min(d,key=len))        
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "PPS.py", line 305, in <module>
    primer_picking_output = pick_primer_pairs(input_file)
  File "PPS.py", line 95, in pick_primer_pairs
    f = open(input_file)
IOError: [Errno 2] No such file or directory: 'TA_2018-09-15T15_05_47_594494/TA_2018-09-15T15_05_47_594494_PSE_out3_1.csv'
```

**Comment by maizeatlas** [comment]
Apologies for the slow response time. Have you resolved this issue? 

There seems to be a problem with the vcf file here. Are you trying to run with masking vcf sites? If so, did you first run the vcf_conversion.py conversion script prior to executing ThermoAlign? If you are not using vcf masking, did you set the variant_mask_condition in the parameters.py file set to 0? Regardless, you could try setting it to 0 to confirm that your vcf input is what's causing the issue.

**Comment by popcornm** [comment]
Hello.
I have the same problem. 
I tried your advice and different ways but i have still the problem. 
My sequence is FASTA format and single files. 
I changed "parameters.py" 
chr_no "1" and my FASTA sequence document name is chr1.FASTA in the sample_genome folder.
How can I made the program generate primer for my sequence?

```
root@0e4ae78eede3:/TA_codes# python vcf_conversion.py

Time to run code =  0.00  seconds 

root@0e4ae78eede3:/TA_codes# nano parameters.py
root@0e4ae78eede3:/TA_codes# ./pipeline.sh
Traceback (most recent call last):
  File "TRS.py", line 111, in <module>
    indel_snp_gap_info = variant_mask(chr_no, start_pos, stop_pos, variant_path, refDB_path, out_path, time_stamp, variant_mask_condition) 
  File "TRS.py", line 40, in variant_mask
    Locus = get_Locus(start_pos, stop_pos, chr_no, refDB_path)
  File "TRS.py", line 27, in get_Locus
    fasta_sequences = SeqIO.parse(open(refDB_path+"chr"+str(chr_no)+".fasta"),'fasta')
IOError: [Errno 2] No such file or directory: '../sample_genome/chr1.fasta'
BLAST Database error: No alias or index file found for nucleotide database [../sample_genome/zmv2all] in search path [/TA_codes::]
Traceback (most recent call last):
  File "PSE.py", line 187, in <module>
    genome_read(no_chrs_in_genome)
  File "PSE.py", line 51, in genome_read
    fasta_sequences = SeqIO.parse(open(refDB_path+"chr"+ str(chr_no) +".fasta"),'fasta')
IOError: [Errno 2] No such file or directory: '../sample_genome/chr1.fasta'
Traceback (most recent call last):
  File "PPS.py", line 305, in <module>
    primer_picking_output = pick_primer_pairs(input_file)
  File "PPS.py", line 95, in pick_primer_pairs
    f = open(input_file)
IOError: [Errno 2] No such file or directory: 'TA_2019-02-16T15_58_52_445950/TA_2019-02-16T15_58_52_445950_PSE_out3_1.csv'

```

**Comment by ffrancis** [comment]
**Response to popcornm:**
Please try renaming your fasta file as chr1.fasta (all lower case). If you follow all the instructions given in the gihub README, it should work. 

The error message says: 
`IOError: [Errno 2] No such file or directory: '../ThermoAlign-master/sample_genome/chr1.fasta'`
The script is looking for "chr1.fasta" filename in the specified location and is unable to find it because the file has been named differently (upper case .FASTA)


**[hilsenna](/hilsenna): seems to be having a different issue because of not running vcf_conversion.py conversion script prior to executing ThermoAlign**

**Comment by popcornm** [comment]
I didn't write upper case like these ".FASTA"  
I always write chr1.fasta filename. 
Apologies for these misunderstood.

**Comment by ffrancisaxiomx** [comment]
OK, please make sure the chr1.fasta file is in the **correct path**/location that you are specifying in the parameters.py: "../sample_genome/chr1.fasta". Only then can the script access the sequence data in it.  I hope you will be able to run it. If you are still unable to fix it, try using the unmodified version provided in the sample data and try running it first before moving on to your custom sequence and parameters. 

ThermoAlign has been successfully used by several users following the instructions given in the README: https://github.com/drmaize/ThermoAlign

Do let us know if you need any additional help regarding this.

**Comment by ffrancis** [comment]
OK, please make sure the chr1.fasta file is in the correct path/location that you are specifying in the parameters.py: "../sample_genome/chr1.fasta". Only then can the script access the sequence data in it. I hope you will be able to run it. If you are still unable to fix it, try using the unmodified version provided in the sample data and try running it first before moving on to your custom sequence and parameters.

ThermoAlign has been successfully used by several users following the instructions given in the README: https://github.com/drmaize/ThermoAlign

Do let us know if you need any additional help regarding this.

**Comment by popcornm** [comment]
Thank you for your quick response and interest.
Step by step, Here is what i did;
- I extracted ThermoAlign-master.zip to my desktop.
- the program run with the sample genome. In the sample; ThermoAlign was successfully ran and I got sample output.
“docker cp /yourlocaldirectory/filename.txt <name|container_id>:/filename.txt”
But, when I delete sample genome and add my genome to the file and then I used thermoalign:TA_1.0.0_d; I couldn’t get any result, only errors.

-Firstly, I wrote command: # Command 1:
<<docker run -t -i --name thermoalign_test drmaize/thermoalign:TA_1.0.0_s bash>>
- Then I wrote: # Command 2: move to TA_codes directory
<<cd TA_codes/>>
- After that, I wrote # Command 4 (optional): the vim (or nano) editor can be used to modify design parameters: I wrote: <<nano parameters.py>> and check my parameters.
-Finally, I wrote # Command 5: <<run ThermoAlign: ./pipeline.sh>>

PS: My chr1.fasta file has “>chromosome:XX:1:1:194711:1" headline. 

```
root@0e4ae78eede3:/TA_codes# python vcf_conversion.py

Time to run code =  0.00  seconds 

root@0e4ae78eede3:/TA_codes# nano parameters.py
root@0e4ae78eede3:/TA_codes# ./pipeline.sh
Traceback (most recent call last):
  File "TRS.py", line 111, in <module>
    indel_snp_gap_info = variant_mask(chr_no, start_pos, stop_pos, variant_path, refDB_path, out_path, time_stamp, variant_mask_condition) 
  File "TRS.py", line 40, in variant_mask
    Locus = get_Locus(start_pos, stop_pos, chr_no, refDB_path)
  File "TRS.py", line 27, in get_Locus
    fasta_sequences = SeqIO.parse(open(refDB_path+"chr"+str(chr_no)+".fasta"),'fasta')
IOError: [Errno 2] No such file or directory: '../sample_genome/chr1.fasta'
BLAST Database error: No alias or index file found for nucleotide database [../sample_genome/zmv2all] in search path [/TA_codes::]
Traceback (most recent call last):
  File "PSE.py", line 187, in <module>
    genome_read(no_chrs_in_genome)
  File "PSE.py", line 51, in genome_read
    fasta_sequences = SeqIO.parse(open(refDB_path+"chr"+ str(chr_no) +".fasta"),'fasta')
IOError: [Errno 2] No such file or directory: '../sample_genome/chr1.fasta'
Traceback (most recent call last):
  File "PPS.py", line 305, in <module>
    primer_picking_output = pick_primer_pairs(input_file)
  File "PPS.py", line 95, in pick_primer_pairs
    f = open(input_file)
IOError: [Errno 2] No such file or directory: 'TA_2019-02-16T15_58_52_445950/TA_2019-02-16T15_58_52_445950_PSE_out3_1.csv'

```
