### ISSUE TITLE
Error in PPS

### ISSUE THREAD

**Issue by jeb486** [drmaize/ThermoAlign#6]
Hi, 

I'm trying to run ThermoAlign with a custom reference genome, and am running into the following error:

Traceback (most recent call last):
  File "PPS.py", line 305, in <module>
    primer_picking_output = pick_primer_pairs(input_file)
  File "PPS.py", line 103, in pick_primer_pairs
    max_misprimeTm=float(max_misprimeTm)
ValueError: could not convert string to float: No match

I've noticed that the PSE_out1_1.csv and PSE_out2_1.csv are empty, and in the PSE_out3_1.csv file, while there are primer entries, the 'max_misprimeTm' column just has 'No match' values for all of the entries.

Is this because blastn is not finding any other matches during priming specificity evaluation? 
So far I've tried:
Increasing max_target_seqs and max_hsps in the UOD section of the parameters file as high as 10 for both. 
Increasing mp_max_hsps to 100 and lowered mp_perc_identity to 70 to try and get more hits. 

However, I'm still getting the same error. 

I can inlcude any of these files if it's helpful!

Thanks!

**Comment by ffrancis** [comment]
@jeb486 Thanks for using Thermoalign. If the PSE output files are empty, it is likely because none of the previously selected primers from UOD are unique in comparison to your reference genome. You can try using a broader range for the following parameters and re-run from UOD.py:

_### PCR conditions
primer_size_range   =   "24-27"
GC_range            =   "30-60"
Tm_range            =   "64-74"_

Please also make sure you are able to run ThermoAlign using the sample_genome and sample_vcf files, using the default parameter.py to make sure all the dependencies (including blastn) have been set up correctly.
